language: node_js
node_js:
  - "4"
  - "6"
# node_js 4 requires gcc 4.8
env:
  - NODE_ENV=travis CXX="g++-4.8"
# gcc 4.8 requires ubuntu-toolchain-r-test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
before_install:
  - sudo apt-get install graphicsmagick
script: npm run test:coverage:check
after_script: npm run coveralls
